import * as THREE from 'three';
import {qualities,chances,costs,gems,specials,stats,recipeFor,rollQuality,COLS,ROWS,pads,start,end,key,fullRoute} from './data.js';
const $=id=>document.getElementById(id);
let wave=1,gold=40,lives=20,quality=0,phase='build',draft=[],draftIndex=0,selected=null,towers=[],rocks=[],enemies=[],effects=[],spawned=0,spawnTimer=0,speed=1,paused=false,showRoute=true,sound=false,route=[],time=0;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2('#1a291f',.012);
const renderer=new THREE.WebGLRenderer({canvas:$('game'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#1a281e',0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
const camera=new THREE.PerspectiveCamera(36,1,.1,150);let zoom=1;
scene.add(new THREE.HemisphereLight('#e5f4c7','#354126',2.1));const sun=new THREE.DirectionalLight('#ffe9be',3.5);sun.position.set(-15,28,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-24,right:24,top:22,bottom:-22});sun.shadow.bias=-.001;scene.add(sun);const rim=new THREE.DirectionalLight('#94cda7',1);rim.position.set(15,8,-15);scene.add(rim);
const board=new THREE.Group();scene.add(board);
const pos=(c,r)=>new THREE.Vector3((c-(COLS-1)/2+(r%2)*.5)*1.04,0,(r-(ROWS-1)/2)*.9);
const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.9,...extra});
const soil=mat('#414732'),edge=mat('#263528'),hexGeo=new THREE.CylinderGeometry(.585,.59,.25,6);
const tiles=[],tileMats=[];let rng=321;function random(){rng=(rng*1664525+1013904223)>>>0;return rng/4294967296;}
const protectedCells=new Set([start,...pads,end].map(p=>key(...p)));
function mesh(geo,material,parent=board){const m=new THREE.Mesh(geo,material);parent.add(m);return m;}
// Layered moss texture provides fine grain and irregular patches across the hex terrain.
const textureCanvas=document.createElement('canvas');textureCanvas.width=textureCanvas.height=256;const tc=textureCanvas.getContext('2d');tc.fillStyle='#839164';tc.fillRect(0,0,256,256);for(let i=0;i<16000;i++){tc.fillStyle=random()>.5?`rgba(28,46,21,${random()*.16})`:`rgba(208,196,138,${random()*.22})`;tc.fillRect(random()*256,random()*256,random()*4+1,random()*4+1);}for(let i=0;i<30;i++){let x=random()*256,y=random()*256,g=tc.createRadialGradient(x,y,0,x,y,35);g.addColorStop(0,'#2e522a55');g.addColorStop(1,'#2e522a00');tc.fillStyle=g;tc.fillRect(x-35,y-35,70,70);}const groundTexture=new THREE.CanvasTexture(textureCanvas);groundTexture.colorSpace=THREE.SRGBColorSpace;
for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){let n=random(),color=new THREE.Color().setHSL(.20+n*.045,.19+n*.1,.23+n*.12);let material=mat(color,{map:groundTexture});tileMats.push(material);let t=mesh(hexGeo,material);t.position.copy(pos(c,r));t.position.y=-.13+random()*.04;t.receiveShadow=true;t.userData={c,r,base:color.clone()};tiles.push(t);let base=mesh(new THREE.CylinderGeometry(.59,.55,.65,6),edge);base.position.copy(t.position);base.position.y=-.55;}
const under=mesh(new THREE.BoxGeometry(20.3,.6,15.5),mat('#293627'));under.position.set(.25,-.8,0);
function ring(position,radius,color,parent=board){const m=mesh(new THREE.RingGeometry(radius*.88,radius,48),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.55,side:THREE.DoubleSide,depthWrite:false}),parent);m.rotation.x=-Math.PI/2;m.position.copy(position);m.position.y=.07;return m;}
function label(text,position,color='#e9e6bb',size=.9){let cv=document.createElement('canvas');cv.width=128;cv.height=128;let ctx=cv.getContext('2d');ctx.font='500 68px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=color;ctx.fillText(text,64,64);let tex=new THREE.CanvasTexture(cv),s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:false}));s.scale.set(size,size,1);s.position.copy(position);s.position.y=.4;board.add(s);return s;}
pads.forEach((p,i)=>{let v=pos(...p);let pad=mesh(new THREE.CylinderGeometry(.49,.53,.09,6),mat('#777e51',{metalness:.3}));pad.position.copy(v);pad.position.y=.065;ring(v,.43,'#e9dca0');label(String(i+1),v);});
function portal(p,color){let v=pos(...p);const group=new THREE.Group();group.position.copy(v);board.add(group);let arch=mesh(new THREE.TorusGeometry(.65,.17,5,12,Math.PI),mat('#687259'),group);arch.position.y=.28;let inner=mesh(new THREE.CircleGeometry(.51,24),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.45,side:THREE.DoubleSide}),group);inner.position.y=.3;ring(v,.8,color);for(let i=0;i<2;i++){let pillar=mesh(new THREE.DodecahedronGeometry(.33),mat('#626b51'),group);pillar.position.set(i?-.62:.62,.15,0);pillar.scale.y=1.5;}}
portal(start,'#d4ad6c');portal(end,'#a5efc9');label('IN',pos(...start).add(new THREE.Vector3(-.1,0,1)), '#dfc791',.75);label('OUT',pos(...end).add(new THREE.Vector3(0,0,-1)),'#a0d5b4',.75);
// Hand-built low-poly forest, weathered stones, and grass create an island diorama.
const trunkMat=mat('#655a3b'),leaves=[mat('#3b603d'),mat('#547044'),mat('#6b7f49')],stoneMat=[mat('#68715b'),mat('#7c8063'),mat('#4c5b46')];
function tree(x,z,s=1){let g=new THREE.Group();g.position.set(x,-.1,z);g.scale.setScalar(s);board.add(g);let tr=mesh(new THREE.CylinderGeometry(.08,.15,1.1,5),trunkMat,g);tr.position.y=.5;for(let j=0;j<3;j++){let leaf=mesh(new THREE.ConeGeometry(.65-j*.13,.95,6),leaves[j],g);leaf.position.y=1+j*.4;leaf.rotation.y=random();leaf.castShadow=true;}return g;}
for(let i=0;i<85;i++){let side=i%4,x,z;if(side<2){x=(random()-.5)*23;z=(side?1:-1)*(8+random()*2.1);}else{x=(side===2?1:-1)*(10.5+random()*2);z=(random()-.5)*17;}if(random()>.23)tree(x,z,.5+random()*.85);else{let s=mesh(new THREE.DodecahedronGeometry(.3+random()*.6),stoneMat[i%3]);s.position.set(x,-.2,z);s.scale.set(1,.6,1);s.castShadow=true;}}
for(let i=0;i<120;i++){let c=Math.floor(random()*COLS),r=Math.floor(random()*ROWS);if(protectedCells.has(key(c,r)))continue;let v=pos(c,r);let pebble=mesh(new THREE.DodecahedronGeometry(.025+random()*.05),stoneMat[i%3]);pebble.position.copy(v).add(new THREE.Vector3((random()-.5)*.65,.04,(random()-.5)*.65));}
let routeGroup=new THREE.Group();board.add(routeGroup);function blocked(){return new Set([...towers,...rocks].map(t=>key(t.c,t.r)));}function updateRoute(){route=fullRoute(blocked())||route;while(routeGroup.children.length){let m=routeGroup.children[0];routeGroup.remove(m);m.geometry?.dispose();m.material?.dispose();}for(let i=1;i<route.length;i++){let a=pos(...route[i-1]),b=pos(...route[i]);for(let k=0;k<2;k++){let v=a.clone().lerp(b,(k+.5)/2);let dot=mesh(new THREE.SphereGeometry(.055,6,5),new THREE.MeshBasicMaterial({color:'#e4cf91',transparent:true,opacity:.9}),routeGroup);dot.position.copy(v);dot.position.y=.11;}}routeGroup.visible=showRoute;}
const hover=mesh(new THREE.CylinderGeometry(.565,.565,.025,6),new THREE.MeshBasicMaterial({color:'#dbecae',transparent:true,opacity:.28}));hover.visible=false;const selectionRing=ring(new THREE.Vector3(),.72,'#e4edb0');selectionRing.visible=false;const rangeRing=ring(new THREE.Vector3(),3,'#bcdf9e');rangeRing.visible=false;
function gemModel(t){let g=new THREE.Group();g.position.copy(pos(t.c,t.r));board.add(g);let s=stats(t),m=mat(s.color,{metalness:.25,roughness:.22,emissive:s.color,emissiveIntensity:.17,flatShading:true});let plinth=mesh(new THREE.CylinderGeometry(.32,.43,.22,6),mat('#788267',{metalness:.2}),g);plinth.position.y=.11;plinth.castShadow=true;const q=t.q||0;let geom=q===0?new THREE.OctahedronGeometry(.31):q===1?new THREE.TetrahedronGeometry(.42):q===2?new THREE.OctahedronGeometry(.4):q===3?new THREE.DodecahedronGeometry(.38):new THREE.IcosahedronGeometry(.43);let crystal=mesh(geom,m,g);crystal.position.y=.58;crystal.scale.set(.8,1.45,.8);crystal.castShadow=true;t.crystal=crystal;if(specials[t.type]){crystal.geometry.dispose();let form=Object.keys(specials).indexOf(t.type);crystal.geometry=form%3===0?new THREE.IcosahedronGeometry(.42):form%3===1?new THREE.DodecahedronGeometry(.4):new THREE.OctahedronGeometry(.42);for(let i=0;i<3+form%3;i++){let shard=mesh(new THREE.OctahedronGeometry(.18),m,g);shard.position.set(Math.cos(i*Math.PI*2/(3+form%3))*.35,.47,Math.sin(i*Math.PI*2/(3+form%3))*.35);shard.scale.y=1.7;}let halo=mesh(new THREE.TorusGeometry(.48,.022,5,32),new THREE.MeshBasicMaterial({color:s.color}),g);halo.rotation.x=Math.PI/2;halo.position.y=.6;t.halo=halo;}ring(new THREE.Vector3(0,0,0),.37,s.color,g);t.model=g;t.timer=0;t.pulse=0;}
function rockModel(t){let g=new THREE.Group();g.position.copy(pos(t.c,t.r));board.add(g);for(let i=0;i<3;i++){let rock=mesh(new THREE.DodecahedronGeometry(i?.2:.35),stoneMat[i],g);rock.position.set(i?(i===1?.2:-.2):0,i?.15:.22,i?.13:0);rock.rotation.set(random(),random(),random());rock.scale.y=.8;rock.castShadow=true;}t.model=g;}
function removeModel(t){board.remove(t.model);t.model.traverse(o=>{if(o.geometry)o.geometry.dispose();});}
function toRock(t){removeModel(t);towers=towers.filter(x=>x!==t);let r={c:t.c,r:t.r,type:'Rock'};rocks.push(r);rockModel(r);}
function makeDraft(){draft=wave===1?['Opal','Emerald','Aquamarine','Ruby','Sapphire'].map(type=>({type,q:0,placed:false})):Array.from({length:5},()=>({type:Object.keys(gems)[Math.floor(Math.random()*8)],q:rollQuality(quality),placed:false}));draftIndex=0;selected=null;selectionRing.visible=false;rangeRing.visible=false;phase='build';renderUI();}
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('show'),3200);}
function select(t){selected=t;selectionRing.visible=!!t;rangeRing.visible=!!t&&t.type!=='Rock';if(t){selectionRing.position.copy(pos(t.c,t.r));selectionRing.position.y=.08;if(t.type!=='Rock'){rangeRing.position.copy(selectionRing.position);rangeRing.scale.setScalar(stats(t).range/30/3);}}renderInspector();renderUI(false);}
function place(c,r){if(phase!=='build')return toast('Select a gem to inspect your defenses.');if(draft.filter(d=>d.placed).length===5)return toast('Choose one of your new gems to keep or combine.');if(protectedCells.has(key(c,r)))return toast('Keep the entrance, exit, and checkpoints clear.');let set=blocked();set.add(key(c,r));if(!fullRoute(set))return toast('That placement blocks a checkpoint. Keep the route open.');let d=draft[draftIndex];if(!d||d.placed){draftIndex=draft.findIndex(d=>!d.placed);d=draft[draftIndex];}let t={type:d.type,q:d.q,c,r,fresh:true,level:0};towers.push(t);gemModel(t);d.placed=true;d.tower=t;draftIndex=draft.findIndex(d=>!d.placed);updateRoute();select(t);renderUI();tone(350+t.q*100);if(draftIndex<0)toast('All five placed. Keep your favorite or craft a special gem.');}
function keep(t){if(phase!=='build'||draft.some(d=>!d.placed)||!t.fresh)return;for(let other of [...towers])if(other.fresh&&other!==t)toRock(other);t.fresh=false;phase='ready';select(t);updateRoute();renderUI();toast(`${t.type} is ready. Release the wave when you are.`);}
function combine(t,type){if(phase==='combat')return;let ingredients=type?recipeFor(type,towers,t):towers.filter(x=>x.type===t.type&&x.q===t.q&&x!==t).slice(0,1);if(!ingredients?.length)return;if(type){for(let other of ingredients)if(other!==t)toRock(other);t.type=type;t.q=0;t.level=0;}else{toRock(ingredients[0]);t.q++;}removeModel(t);gemModel(t);if(t.fresh&&draft.every(d=>d.placed))keep(t);else{updateRoute();select(t);renderUI();}toast(type?`${type} forged. A new kind of brilliance.`:`Upgraded to ${qualities[t.q]} ${t.type}.`);tone(650);}
function renderInspector(){let root=$('inspector');if(!selected){root.innerHTML='<div class="inspector-empty"><div class="empty-gem">♢</div><h3>A gem of an idea</h3><p>Select a placed gem to view its stats,<br>abilities, and possible combinations.</p><div class="inspector-hint">◇ &nbsp; Every gem has something to offer.</div></div>';return;}let t=selected;if(t.type==='Rock'){root.innerHTML='<div class="inspect-gem-heading"><span class="empty-gem">⬡</span><div><h3>Weathered rock</h3><p>A wall that shapes the enemy route.</p></div></div><p class="effect-text">Remove this rock to open a hex. Removing walls always keeps the route accessible.</p><div class="inspect-actions"><button id="remove-rock">Remove rock · Free</button></div>';$('remove-rock').onclick=()=>{removeModel(t);rocks=rocks.filter(r=>r!==t);select(null);updateRoute();};return;}let s=stats(t),recipes=Object.keys(specials).filter(name=>recipeFor(name,towers,t));root.innerHTML=`<div class="inspect-gem-heading"><span class="gem-icon" style="--gem:${s.color}"></span><div><h3>${t.type}</h3><p>${specials[t.type]?`Special gem · Level ${(t.level||0)+1}`:qualities[t.q]+' · '+(t.fresh?'Newly placed':'Kept gem')}</p></div></div><div class="gem-stats"><span><small>DAMAGE</small>${s.damage.map(Math.round).join('–')}</span><span><small>COOLDOWN</small>${s.cooldown}ms</span><span><small>RANGE</small>${s.range}</span></div><p class="effect-text">${s.effect}</p><div class="inspect-actions">${t.fresh&&draft.every(d=>d.placed)&&phase==='build'?'<button class="keep" id="keep-gem">Keep this gem</button>':''}${!specials[t.type]&&t.q<4&&towers.some(x=>x!==t&&x.type===t.type&&x.q===t.q)&&phase!=='combat'?'<button id="combine-gem">Combine pair ↑</button>':''}${t.q>0&&!specials[t.type]&&phase!=='combat'?'<button id="reduce-gem">Reduce quality ↓</button>':''}${specials[t.type]?`<button id="upgrade-special" ${gold<specialCost(t)?'disabled':''}>Upgrade · ◈ ${specialCost(t)}</button>`:''}</div>${recipes.length?'<p class="recipe-message">✦ Special recipe available. This gem will become:</p><div class="inspect-actions">'+recipes.map(name=>`<button data-recipe="${name}">${name} ✧</button>`).join('')+'</div>':'<p class="recipe-message">◇ Select matching ingredients to discover special recipes.</p>'}`;
$('keep-gem')?.addEventListener('click',()=>keep(t));$('combine-gem')?.addEventListener('click',()=>combine(t));$('reduce-gem')?.addEventListener('click',()=>{t.q--;removeModel(t);gemModel(t);select(t);});$('upgrade-special')?.addEventListener('click',()=>{if(gold<specialCost(t))return;gold-=specialCost(t);t.level=(t.level||0)+1;select(t);toast('Special gem upgraded.');});root.querySelectorAll('[data-recipe]').forEach(b=>{b.disabled=phase==='combat'||(phase==='build'&&draft.some(d=>!d.placed));b.onclick=()=>combine(t,b.dataset.recipe);});}
const specialCost=t=>40+40*(t.level||0);
function waveInfo(){return wave%5===0?{name:'Ancient guardian',count:3,boss:true,air:false}:wave%4===0?{name:'Skywing swarm',count:10+wave,air:true,boss:false}:{name:wave%3===0?'Armored beetles':'Forest crawlers',count:10+wave*2,air:false,boss:false};}
function renderUI(inspector=true){$('wave').textContent=String(wave).padStart(2,'0');$('gold').textContent=Number(gold.toFixed(1));$('lives').innerHTML=`${lives}<span> / 20</span>`;let info=waveInfo();$('enemy-name').textContent=info.name;$('enemy-count').textContent=`${info.count} enemies`;let placed=draft.filter(d=>d.placed).length;$('phase-label').textContent=phase==='combat'?'DEFEND PHASE':phase==='ready'?'READY TO DEFEND':phase==='over'?'EXPEDITION ENDED':'BUILD PHASE';$('draft-count').textContent=phase==='combat'?`${spawned} / ${info.count} RELEASED`:`${placed} / 5 PLACED`;$('draft-heading').textContent=phase==='combat'?'Let your gems shine':phase==='ready'?'Your defense is ready':placed===5?'Choose your keeper':'Place your gems';$('draft-desc').textContent=phase==='combat'?'Watch the crossing. Every gem makes a difference.':placed===5?'Keep one gem, or combine a recipe. The rest become walls.':'Five possibilities. One to keep. Make every placement count.';$('draft-note').innerHTML=wave===1?'A little luck to start: your first hand can form <b>Malachite</b>.':'Tip: combine matching gems to reach the next quality.';$('draft-cards').innerHTML=draft.map((d,i)=>`<button class="gem-card ${i===draftIndex?'selected':''} ${d.placed?'placed':''}" data-card="${i}" aria-label="Select ${qualities[d.q]} ${d.type}"><span class="card-number">${d.placed?'✓':String(i+1).padStart(2,'0')}</span><span class="gem-icon" style="--gem:${gems[d.type].color}"></span><b>${d.type}</b><small>${qualities[d.q]}</small></button>`).join('');$('draft-cards').querySelectorAll('button').forEach(b=>b.onclick=()=>{let i=+b.dataset.card;if(draft[i].placed){let t=towers.find(t=>t===draft[i].tower);if(t)select(t);else toast('This gem has become a rock.');}else{draftIndex=i;select(null);renderUI();}});let wb=$('wave-button');wb.disabled=phase!=='ready';wb.innerHTML=phase==='combat'?'Wave in progress <span>⌁</span>':phase==='ready'?'Release wave <span>→</span>':'Keep a gem to begin <span>→</span>';$('quality-level').textContent=`LEVEL ${quality}`;$('quality-next').textContent=quality<8?`NEXT: LEVEL ${quality+1}`:'MAXIMUM QUALITY';$('quality-segments').innerHTML=Array.from({length:8},(_,i)=>`<i class="${i<quality?'on':''}"></i>`).join('');$('odds').innerHTML=chances[quality].map((n,i)=>n?`<span>${qualities[i]} <b>${n}%</b></span>`:'').join('');$('upgrade').disabled=quality===8||gold<costs[quality];$('upgrade').innerHTML=quality===8?'Quality mastered ✧':`Upgrade quality <span>◈ &nbsp;${costs[quality]}</span>`;if(inspector)renderInspector();}
$('upgrade').onclick=()=>{if(quality<8&&gold>=costs[quality]){gold-=costs[quality++];renderUI();toast('Quality odds improved for your next hand.');}};
let audioContext;function tone(freq){if(!sound)return;try{audioContext??=new AudioContext();let o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.frequency.value=freq;g.gain.setValueAtTime(.025,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.12);o.start();o.stop(audioContext.currentTime+.13);}catch{}}
function startWave(){if(phase!=='ready')return;phase='combat';spawned=0;spawnTimer=.2;enemies=[];renderUI();tone(200);}
$('wave-button').onclick=startWave;
function spawnEnemy(){let info=waveInfo(),boss=info.boss&&spawned===info.count-1,air=info.air;let g=new THREE.Group();board.add(g);let material=mat(boss?'#b49577':air?'#b9a3d1':'#b2a071',{metalness:.15});let body=mesh(new THREE.IcosahedronGeometry(boss?.39:.19,0),material,g);body.scale.set(.9,.65,1.25);body.castShadow=true;let shell=mesh(new THREE.IcosahedronGeometry(boss?.28:.135,0),mat(boss?'#6f6b52':'#71834f'),g);shell.position.set(0,.1,-.06);let eyeMat=new THREE.MeshBasicMaterial({color:'#ffcb86'});for(let n of [-1,1]){let eye=mesh(new THREE.SphereGeometry(.035,5,5),eyeMat,g);eye.position.set(n*.075,.04,.18);if(air){let wing=mesh(new THREE.OctahedronGeometry(.27),mat('#b6c6bd',{transparent:true,opacity:.65}),g);wing.scale.set(1,.07,.5);wing.position.x=n*.24;}}
let routePoints=air?[start,...pads,end].map(p=>pos(...p)):route.map(p=>pos(...p));let hp=(22+wave*13)*Math.pow(1.11,wave-1)*(boss?12:info.boss?3:1);let e={model:g,material,baseColor:material.color.clone(),hp,maxHp:hp,armor:boss?12:wave%3===0?4:0,air,boss,path:routePoints,index:1,speed:air?2.25:boss?1.3:1.8+wave*.018,slow:0,slowTime:0,dot:0,dotTime:0,stun:0,dead:false};g.position.copy(routePoints[0]);g.position.y=air?1:.25;let health=mesh(new THREE.PlaneGeometry(.48,.045),new THREE.MeshBasicMaterial({color:'#c8e693',side:THREE.DoubleSide}),g);health.position.y=boss?.8:.45;health.rotation.x=-.7;e.health=health;enemies.push(e);spawned++;renderUI(false);}
function fx(a,b,color,kind='bolt'){let m;if(kind==='wave'){m=ring(a,.3,color);m.position.y=.18;}else{let geo=new THREE.BufferGeometry().setFromPoints([a,b]);m=new THREE.Line(geo,new THREE.LineBasicMaterial({color,transparent:true,opacity:1}));board.add(m);}effects.push({m,life:kind==='wave'?.75:.2,max:kind==='wave'?.75:.2,kind});}
function hit(e,amount,t){if(e.dead)return;let armor=e.armor;for(let a of towers){if(a.type==='Red Crystal'&&e.air&&a.model.position.distanceTo(e.model.position)<200/30)armor-=5+Math.min(a.level||0,2);if(a.type==='Paraiba Tourmaline'&&!e.air&&a.model.position.distanceTo(e.model.position)<86/30)armor-=4;}e.hp-=Math.max(.5,amount*(1-Math.max(-.5,armor*.035)));if(e.hp<=0){e.dead=true;board.remove(e.model);gold+=1.5+(wave-1)*.25+(t?.type==='Jade'&&t.level>=2?1:0);fx(e.model.position,e.model.position,stats(t||{type:'Ruby',q:0}).color,'wave');renderUI(false);}}
function status(e,kind,amount,duration){if(kind==='slow'){e.slow=Math.max(e.slow,amount);e.slowTime=Math.max(e.slowTime,duration);}else{e.dot=Math.max(e.dot,amount);e.dotTime=Math.max(e.dotTime,duration);e.dotKind=kind;}}
function shoot(t,target){let s=stats(t),damage=s.damage[0]+Math.random()*(s.damage[1]-s.damage[0]);let name=t.type;if((name==='Diamond'||name==='Gold')&&Math.random()<.25)damage*=2;if(name==='Pink Diamond'&&Math.random()<.1)damage*=5;for(let a of towers)if(a.type==='Black Opal'&&a.model.position.distanceTo(t.model.position)<143/30)damage*=1.3;let from=t.model.position.clone();from.y=.7;fx(from,target.model.position,s.color);hit(target,damage,t);if(name==='Sapphire')status(target,'slow',.25+t.q*.05,2);if(name==='Emerald'){status(target,'poison',[2,3,5,8,16][t.q],[3,4,5,6,8][t.q]);status(target,'slow',[.15,.2,.25,.35,.5][t.q],[3,4,5,6,8][t.q]);}if(name==='Jade'){status(target,'poison',5,2);status(target,'slow',.5,2);}if(name==='Dark Emerald'&&Math.random()<.125)target.stun=1;if(['Ruby','Blood Stone','Silver','Yellow Sapphire'].includes(name)){let radius=name==='Silver'?36:57;fx(target.model.position,target.model.position,s.color,'wave');for(let e of enemies)if(!e.dead&&e.model.position.distanceTo(target.model.position)<radius/30){if(e!==target)hit(e,damage*.65,t);if(name==='Blood Stone')status(e,'fire',135,3);if(name==='Silver'||name==='Yellow Sapphire')status(e,'slow',.2,2);}}if(name==='Paraiba Tourmaline'&&Math.random()<.33){fx(target.model.position,target.model.position,'#bbf9f6','wave');for(let e of enemies)if(!e.dead&&e.model.position.distanceTo(target.model.position)<2){hit(e,100,t);status(e,'slow',.6,2);}}}
function combat(dt){spawnTimer-=dt;let info=waveInfo();if(spawned<info.count&&spawnTimer<=0){spawnEnemy();spawnTimer=info.boss?2.5:.8;}for(let e of enemies){if(e.dead)continue;e.slowTime-=dt;e.dotTime-=dt;e.stun-=dt;if(e.slowTime<=0)e.slow=0;if(e.dotTime>0)hit(e,e.dot*dt,e.lastTower);if(e.dead)continue;e.material.color.copy(e.baseColor);if(e.stun>0||e.slowTime>0)e.material.color.set('#7bbdff');if(e.dotTime>0)e.material.color.set(e.dotKind==='fire'?'#ff8760':e.dotKind==='radiation'?'#dafd60':'#78e56d');let dest=e.path[e.index];if(dest&&e.stun<=0){let d=new THREE.Vector3(dest.x-e.model.position.x,0,dest.z-e.model.position.z);let step=e.speed*(1-e.slow)*dt;if(d.length()<step){e.model.position.x=dest.x;e.model.position.z=dest.z;e.index++;}else{d.normalize();e.model.position.addScaledVector(d,step);e.model.rotation.y=Math.atan2(d.x,d.z);}e.model.position.y=(e.air?1:.24)+Math.sin(time*(e.air?8:13)+e.index)*.035;}e.health.scale.x=Math.max(0,e.hp/e.maxHp);if(e.index>=e.path.length){e.dead=true;board.remove(e.model);lives=Math.max(0,lives-(e.boss?5:1));renderUI(false);if(!lives){gameOver();return;}}}
for(let t of towers){let s=stats(t);t.timer-=dt;t.pulse-=dt;let range=s.range/30;let targets=enemies.filter(e=>!e.dead&&t.model.position.distanceTo(e.model.position)<range&&(!['Diamond','Pink Diamond'].includes(t.type)||!e.air)&&(!['Amethyst','Red Crystal'].includes(t.type)||e.air));if(['Star Ruby','Uranium 238'].includes(t.type)){for(let e of targets){if(t.type==='Uranium 238'&&e.model.position.distanceTo(t.model.position)>64/30)continue;hit(e,(t.type==='Star Ruby'?40:260)*dt,t);status(e,t.type==='Star Ruby'?'fire':'radiation',0,.3);if(t.type==='Uranium 238')status(e,'slow',.5,.3);}if(targets.length&&t.pulse<=0){fx(t.model.position,t.model.position,s.color,'wave');t.pulse=.7;}}if(t.type==='Opal'&&t.pulse<=0){fx(t.model.position,t.model.position,s.color,'wave');t.pulse=2;}if(t.timer<=0&&targets.length){let boost=0;for(let a of towers)if(a.type==='Opal'&&a!==t&&a.model.position.distanceTo(t.model.position)<stats(a).range/30)boost=Math.max(boost,[.1,.15,.2,.25,.35][a.q]);t.timer=s.cooldown/1000/(1+boost);targets.sort((a,b)=>b.index-a.index);let number=['Topaz','Malachite'].includes(t.type)?3:1;targets.slice(0,number).forEach(e=>{e.lastTower=t;shoot(t,e);});t.crystal.scale.y=1.8;}}
enemies=enemies.filter(e=>!e.dead);if(spawned>=info.count&&enemies.length===0){gold+=10+(wave-1)*2;wave++;phase='build';toast(`Wave cleared! +${10+(wave-2)*2} gold. A new hand awaits.`);makeDraft();}}
function gameOver(){phase='over';showModal(`<span class="eyebrow">EXPEDITION COMPLETE</span><h2>The crossing falls silent.</h2><p>You reached wave ${wave}. Every maze is a lesson. Build a new defense and try another path.</p><button class="primary-button" id="restart">Begin a new expedition →</button>`);$('restart').onclick=()=>location.reload();renderUI();}
function resize(){let v=$('viewport');renderer.setSize(v.clientWidth,v.clientHeight,false);camera.aspect=v.clientWidth/v.clientHeight;let fit=Math.max(1,1.4/camera.aspect);camera.position.set(12*zoom*fit,32*.86*zoom*fit,19*zoom*fit);camera.lookAt(.5,0,0);camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('viewport'));resize();
function changeZoom(amount){zoom=THREE.MathUtils.clamp(zoom+amount,.65,1.4);resize();}$('zoom-in').onclick=()=>changeZoom(-.1);$('zoom-out').onclick=()=>changeZoom(.1);$('reset-camera').onclick=()=>{zoom=1;resize();};$('route-toggle').onclick=()=>{showRoute=!showRoute;routeGroup.visible=showRoute;$('route-toggle').classList.toggle('active',showRoute);};
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();function tileAt(event){let rect=$('game').getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(tiles)[0]?.object;}
$('game').addEventListener('pointermove',e=>{let tile=tileAt(e);hover.visible=!!tile&&phase==='build';if(tile){hover.position.copy(tile.position);hover.position.y=.08;$('game').style.cursor='pointer';}});$('game').addEventListener('pointerleave',()=>hover.visible=false);$('game').addEventListener('pointerdown',e=>{if(phase==='over')return;let tile=tileAt(e);if(!tile)return;let {c,r}=tile.userData,t=[...towers,...rocks].find(t=>t.c===c&&t.r===r);if(t)select(t);else place(c,r);});$('game').addEventListener('wheel',e=>{e.preventDefault();changeZoom(e.deltaY*.0004);},{passive:false});
let keyboardCell=[9,8];document.addEventListener('keydown',e=>{if($('modal').open)return;if(e.key==='Escape'){select(null);return;}if(e.key===' '){e.preventDefault();if(phase==='ready')startWave();else togglePause();}if('12345'.includes(e.key)){let i=+e.key-1;if(!draft[i].placed){draftIndex=i;renderUI();}else if(towers.includes(draft[i].tower))select(draft[i].tower);}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();keyboardCell[0]=THREE.MathUtils.clamp(keyboardCell[0]+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0),0,COLS-1);keyboardCell[1]=THREE.MathUtils.clamp(keyboardCell[1]+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0),0,ROWS-1);hover.visible=true;hover.position.copy(pos(...keyboardCell));hover.position.y=.08;}if(e.key==='Enter'){let [c,r]=keyboardCell,t=[...towers,...rocks].find(t=>t.c===c&&t.r===r);t?select(t):place(c,r);}if(e.key.toLowerCase()==='k'&&selected)keep(selected);if(e.key==='+'||e.key==='=')changeZoom(-.1);if(e.key==='-')changeZoom(.1);});
function togglePause(){paused=!paused;$('pause').textContent=paused?'▶ Resume':'Ⅱ Pause';$('footer-status').textContent=paused?'Expedition paused.':'Build thoughtfully. Defend brilliantly.';}$('pause').onclick=togglePause;$('speed').onclick=()=>{speed=speed===1?2:speed===2?3:1;$('speed').textContent=`${speed}× Speed`;};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫':'♩';$('sound').style.color=sound?'#d5ed9a':'';toast(sound?'Sound on':'Sound off');tone(500);};
function showModal(html){$('modal-content').innerHTML=html;$('modal').showModal();}$('close-modal').onclick=()=>$('modal').close();$('modal').addEventListener('click',e=>{if(e.target===$('modal'))$('modal').close();});
$('help').onclick=()=>showModal(`<span class="eyebrow">WELCOME TO 4HEX</span><h2>A little strategy.<br>A lot of brilliance.</h2><p><b>1. Place five gems.</b> Select a gem in your hand, then click or tap an empty hex. All six checkpoints must remain accessible.</p><p><b>2. Choose your keeper.</b> After placing all five, select one and keep it. The others become rocks. Or select an ingredient and combine a special recipe—the chosen hex becomes your special gem.</p><p><b>3. Defend the crossing.</b> Release the wave. Enemies visit checkpoints 1–6 in order before escaping. Every fourth wave flies over walls; every fifth brings a boss.</p><p><b>Refine your strategy.</b> Remove rocks for free. Combine two gems of the same type and quality. Reduce quality to fit recipes. Spend gold on better future draft odds or special gem upgrades.</p><p><b>Keyboard:</b> 1–5 selects a draft gem · arrow keys choose a hex · Enter places/selects · K keeps · Space starts or pauses · +/− zooms · Esc deselects.</p>`);
$('guide').onclick=()=>showModal(`<span class="eyebrow">THE ALCHEMIST'S FIELD GUIDE</span><h2>More than the sum of their gems.</h2><p>Place the ingredients, then select the gem whose position you want to keep. The other ingredients become rocks. Quality upgrades affect your next hand.</p><div class="recipe-list">${Object.entries(specials).map(([name,s])=>`<div class="recipe-entry"><b>${name}</b>${s.recipe.map(([n,q])=>`${qualities[q]} ${n}`).join(' + ')}<br><span>${s.effect}</span></div>`).join('')}</div>`);
let last=performance.now();function animate(now){requestAnimationFrame(animate);let dt=Math.min((now-last)/1000,.05);last=now;if(!paused&&!$('modal').open){time+=dt;for(let t of towers){t.crystal.rotation.y+=dt*.35;t.crystal.position.y=.6+Math.sin(time*2+t.c)*.035;t.crystal.scale.y=THREE.MathUtils.lerp(t.crystal.scale.y,1.45,dt*8);if(t.halo){t.halo.rotation.z+=dt;t.halo.position.y=.55+Math.sin(time*2)*.1;}}for(let f of [...effects]){f.life-=dt*speed;f.m.material.opacity=Math.max(0,f.life/f.max)*.65;if(f.kind==='wave')f.m.scale.setScalar(1+(1-f.life/f.max)*7);if(f.life<=0){board.remove(f.m);f.m.geometry.dispose();f.m.material.dispose();effects=effects.filter(x=>x!==f);}}if(phase==='combat')combat(dt*speed);}renderer.render(scene,camera);}updateRoute();makeDraft();requestAnimationFrame(animate);
// A compact debug surface makes route and lifecycle checks reproducible.
window.__game={get state(){return {wave,gold,lives,phase,draft,towers,rocks,enemies,quality,route};},place,select,keep,combine,startWave,worldToScreen(c,r){let p=pos(c,r).project(camera),rect=$('game').getBoundingClientRect();return {x:rect.left+(p.x+1)*rect.width/2,y:rect.top+(1-p.y)*rect.height/2};}};
